#
# Copyright (C) 2015 Samsung Electronics
# Przemyslaw Marczak <p.marczak@samsung.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-$(CONFIG_DM_CHARGER) += charger-uclass.o
obj-$(CONFIG_DM_CHARGER_NXE2000) += nxe2000.o
