#
# (C) Copyright 2017 Samsung
# Jaewon Kim <jaewon02.kim@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_S5P6818_DRONE)	+= drone/
obj-$(CONFIG_TARGET_ARTIK710_RAPTOR)	+= artik710_raptor/
obj-$(CONFIG_TARGET_AVN_REF)	+= avn_ref/
obj-$(CONFIG_TARGET_KICK_ST)	+= kick_st/
obj-$(CONFIG_TARGET_ARTIK711S_RAPTOR)	+= artik711s_raptor/
