#
# (C) Copyright 2017 Samsung
# Jaewon Kim <jaewon02.kim@samsung.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_S5P4418_DRONE)	+= drone/
obj-$(CONFIG_TARGET_ARTIK530_RAPTOR)	+= artik530_raptor/
obj-$(CONFIG_TARGET_S5P4418_AVN_REF)	+= avn_ref/
obj-$(CONFIG_TARGET_S5P4418_NAVI_REF)	+= navi_ref/
obj-$(CONFIG_TARGET_S5P4418_DAUDIO_REF)	+= daudio_ref/
obj-$(CONFIG_TARGET_S5P4418_SMART_VOICE)	+= smart_voice/
obj-$(CONFIG_TARGET_S5P4418_FF_VOICE)	+= ff_voice/
obj-$(CONFIG_TARGET_S5P4418_ZH_DRAGON)	+= zh_dragon/
obj-$(CONFIG_TARGET_S5P4418_ZH_BLACKDRAGON)	+= zh_blackdragon/
obj-$(CONFIG_TARGET_S5P4418_DAUDIO_COVI)	+= daudio_covi/
obj-$(CONFIG_TARGET_S5P4418_CLOVA)	+= clova/
obj-$(CONFIG_TARGET_S5P4418_SVM_REF)	+= svm_ref/
obj-$(CONFIG_TARGET_S5P4418_DAUDIO_CONA)	+= daudio_cona/
obj-$(CONFIG_TARGET_S5P4418_CLUSTER_REF)	+= cluster_ref/
obj-$(CONFIG_TARGET_S5P4418_ALLO_DISPLAY)	+= allo_display/
obj-$(CONFIG_TARGET_S5P4418_CONVERGENCE_SVMC)	+= convergence_svmc/
obj-$(CONFIG_TARGET_S5P4418_CON_SVMA)	+= con_svma/
